### ISSUE TITLE
Can't seem to run it

### ISSUE THREAD

**Issue by mfurlend** [cambecc/grib2json#2]
I ran mvn successfully, but the launch script fails. Both the launch script and this manual execution fail with the same exception:

  #/bin/java -classpath "/root/grib2json/target/classes/net/nullschool/grib2json/" -Xmx256M -jar  grib2json-0.8.0-SNAPSHOT.jar                                                                                                        !4544
  Exception in thread "main" java.lang.NoClassDefFoundError:   com/lexicalscope/jewel/JewelRuntimeException
   at java.lang.Class.getDeclaredMethods0(Native Method)
   at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
   at java.lang.Class.getMethod0(Class.java:2774)
   at java.lang.Class.getMethod(Class.java:1663)
   at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
   at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
  Caused by: java.lang.ClassNotFoundException: com.lexicalscope.jewel.JewelRuntimeException
   at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
 ... 6 more

**Comment by fox91** [comment]
I've the same problem plus others.
These are the commands I used:
```bash
git clone https://github.com/cambecc/grib2json.git
cd grib2json/
mvn package
export JAVA_HOME=/usr
```
now I have two directory: `src/` and `target/`.
If I run the command `bash src/bin/grib2json` (why you not `chmod +x grib2json` in the repository?) it give me `Error: Unable to access jarfile src/bin/../lib/grib2json-*.jar`.

I need to:
```bash
mv src/bin/ ./
mv target/ lib/
```

Now I can run `bash bin/grib2json` but the output is:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/lexicalscope/jewel/JewelRuntimeException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.lexicalscope.jewel.JewelRuntimeException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more
```

**Comment by mftaha** [comment]
Same issue, running it through the script
