### ISSUE TITLE
Non scalar variable error

### ISSUE THREAD

**Issue by b3z** [cambecc/grib2json#42]
```sh
java.lang.UnsupportedOperationException: not a scalar variable =int time(time=97);
  :units = "Hour since 2020-07-10T18:00:00Z";
  :standard_name = "time";
  :long_name = "product valid at RT + P1";

        at ucar.nc2.Variable.getScalarData(Variable.java:796)
        at ucar.nc2.Variable.readScalarInt(Variable.java:731)
        at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:84)
        at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:117)
        at net.nullschool.grib2json.Launcher.main(Launcher.java:75)

```

**Comment by icemagno** [comment]
Same here
