### ISSUE TITLE
java.io.IOException: Negative seek offset

### ISSUE THREAD

**Issue by BenjaminCrozier** [cambecc/grib2json#43]
```
> ./grib2json %HOMEPATH%\Documents\SHI\MRMS_SHI_00.50_20200725-210240.grib2
java.io.IOException: Negative seek offset
        at ucar.unidata.io.RandomAccessFile.seek(RandomAccessFile.java:402)
        at ucar.grib.grib2.Grib2BitMapSection.<init>(Grib2BitMapSection.java:127)
        at ucar.grib.grib2.Grib2Input.scan(Grib2Input.java:227)
        at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:104)
        at net.nullschool.grib2json.Launcher.main(Launcher.java:75)

[
```

data set used: `https://mrms.ncep.noaa.gov/data/2D/SHI/`

**Comment by netwavetech** [comment]
Im seeing the same issue with MRMS data...
